// ---------------------------------------------------------------------------
// Global category feeds (15 categories)
// ---------------------------------------------------------------------------

export const FEEDS = {
  world: [
    { url: 'https://feeds.bbci.co.uk/news/world/rss.xml', source: 'BBC News' },
    { url: 'https://www.aljazeera.com/xml/rss/all.xml', source: 'Al Jazeera' },
    { url: 'https://feeds.npr.org/1004/rss.xml', source: 'NPR' },
    { url: 'https://abcnews.go.com/abcnews/internationalheadlines', source: 'ABC News' },
    { url: 'https://www.theguardian.com/world/rss', source: 'The Guardian' },
    { url: 'https://feedx.net/rss/ap.xml', source: 'AP News' },
    { url: 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml', source: 'NY Times World' },
    { url: 'https://feeds.washingtonpost.com/rss/world', source: 'Washington Post World' },
    { url: 'http://rss.cnn.com/rss/cnn_world.rss', source: 'CNN World' },
    { url: 'https://moxie.foxnews.com/google-publisher/world.xml', source: 'Fox News World' },
    { url: 'https://www.cbsnews.com/latest/rss/world', source: 'CBS News World' },
    { url: 'https://feeds.skynews.com/feeds/rss/world.xml', source: 'Sky News World' },
    { url: 'https://www.independent.co.uk/news/world/rss', source: 'The Independent World' },
    { url: 'https://www.cnbc.com/id/100727362/device/rss/rss.html', source: 'CNBC World' },
    { url: 'https://theconversation.com/global/home-page.atom', source: 'The Conversation' },
    { url: 'http://rssfeeds.usatoday.com/usatoday-NewsTopStories', source: 'USA Today' },
    { url: 'https://rss.dw.com/xml/rss-en-all', source: 'DW News' },
    { url: 'https://www.france24.com/en/rss', source: 'France 24 English' },
    { url: 'https://english.alarabiya.net/tools/mrss', source: 'Al Arabiya English' },
    { url: 'https://www.themoscowtimes.com/rss/news', source: 'Moscow Times' },
    { url: 'https://www.africanews.com/feed/rss', source: 'Africanews' },
    { url: 'https://globalvoices.org/feed/', source: 'Global Voices' },
    { url: 'https://asia.nikkei.com/rss/feed/nar', source: 'Nikkei Asia' },
  ],
  technology: [
    { url: 'https://feeds.bbci.co.uk/news/technology/rss.xml', source: 'BBC Tech' },
    { url: 'https://feeds.npr.org/1019/rss.xml', source: 'NPR Tech' },
    { url: 'https://feeds.arstechnica.com/arstechnica/index', source: 'Ars Technica' },
    { url: 'https://www.theguardian.com/technology/rss', source: 'The Guardian Tech' },
    { url: 'https://www.wired.com/feed/rss', source: 'Wired' },
    { url: 'https://www.engadget.com/rss.xml', source: 'Engadget' },
    { url: 'https://www.cnet.com/rss/news/', source: 'CNET' },
    { url: 'https://www.zdnet.com/news/rss.xml', source: 'ZDNet' },
    { url: 'http://rss.cnn.com/rss/cnn_tech.rss', source: 'CNN Tech' },
    { url: 'https://www.cnbc.com/id/19854910/device/rss/rss.html', source: 'CNBC Tech' },
    { url: 'https://feeds.skynews.com/feeds/rss/technology.xml', source: 'Sky News Tech' },
    { url: 'https://moxie.foxnews.com/google-publisher/tech.xml', source: 'Fox News Tech' },
    { url: 'https://www.theverge.com/rss/index.xml', source: 'The Verge' },
    { url: 'https://techcentral.co.za/feed', source: 'TechCentral SA' },
  ],
  business: [
    { url: 'https://feeds.bbci.co.uk/news/business/rss.xml', source: 'BBC Business' },
    { url: 'https://feeds.npr.org/1006/rss.xml', source: 'NPR Business' },
    { url: 'https://www.cnbc.com/id/10001147/device/rss/rss.html', source: 'CNBC Business' },
    { url: 'http://rss.cnn.com/rss/money_latest.rss', source: 'CNN Business' },
    { url: 'https://feeds.skynews.com/feeds/rss/business.xml', source: 'Sky News Business' },
    { url: 'https://fortune.com/feed/', source: 'Fortune' },
    { url: 'http://feeds2.feedburner.com/businessinsider', source: 'Business Insider' },
    { url: 'https://rss.dw.com/xml/rss-en-bus', source: 'DW Business' },
    { url: 'https://www.moneyweb.co.za/feed/', source: 'Moneyweb SA' },
    { url: 'https://businesstech.co.za/news/feed/', source: 'BusinessTech SA' },
  ],
  science: [
    { url: 'https://feeds.bbci.co.uk/news/science_and_environment/rss.xml', source: 'BBC Science' },
    { url: 'https://feeds.npr.org/1007/rss.xml', source: 'NPR Science' },
    { url: 'http://rss.sciam.com/ScientificAmerican-Global', source: 'Scientific American' },
    { url: 'https://phys.org/rss-feed/', source: 'Phys.org' },
    { url: 'https://moxie.foxnews.com/google-publisher/science.xml', source: 'Fox News Science' },
    { url: 'https://www.cbsnews.com/latest/rss/science', source: 'CBS News Science' },
    { url: 'https://rss.dw.com/xml/rss-en-science', source: 'DW Science' },
    { url: 'https://www.nature.com/nature.rss', source: 'Nature' },
    { url: 'https://www.newscientist.com/feed/home/', source: 'New Scientist' },
  ],
  sport: [
    { url: 'https://feeds.bbci.co.uk/sport/rss.xml', source: 'BBC Sport' },
    { url: 'https://www.espn.com/espn/rss/news', source: 'ESPN' },
    { url: 'https://www.theguardian.com/uk/sport/rss', source: 'The Guardian Sport' },
    { url: 'https://moxie.foxnews.com/google-publisher/sports.xml', source: 'Fox News Sports' },
  ],
  culture: [
    { url: 'https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml', source: 'BBC Arts' },
    { url: 'https://feeds.npr.org/1008/rss.xml', source: 'NPR Arts' },
    { url: 'https://www.theguardian.com/culture/rss', source: 'The Guardian Culture' },
    { url: 'https://rss.dw.com/xml/rss-en-cul', source: 'DW Culture' },
  ],
  environment: [
    { url: 'https://feeds.bbci.co.uk/news/science_and_environment/rss.xml', source: 'BBC Environment' },
    { url: 'https://www.theguardian.com/environment/rss', source: 'The Guardian Environment' },
  ],
  politics: [
    { url: 'https://feeds.bbci.co.uk/news/politics/rss.xml', source: 'BBC Politics' },
    { url: 'https://feeds.npr.org/1014/rss.xml', source: 'NPR Politics' },
    { url: 'https://rss.politico.com/politics-news.xml', source: 'Politico' },
    { url: 'https://thehill.com/news/feed/', source: 'The Hill' },
    { url: 'http://rss.cnn.com/rss/cnn_allpolitics.rss', source: 'CNN Politics' },
    { url: 'https://moxie.foxnews.com/google-publisher/politics.xml', source: 'Fox News Politics' },
    { url: 'https://www.cnbc.com/id/10000113/device/rss/rss.html', source: 'CNBC Politics' },
    { url: 'https://feeds.skynews.com/feeds/rss/politics.xml', source: 'Sky News Politics' },
  ],
  ai: [
    { url: 'https://techcrunch.com/category/artificial-intelligence/feed/', source: 'TechCrunch AI' },
    { url: 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml', source: 'The Verge AI' },
    { url: 'https://www.technologyreview.com/feed/', source: 'MIT Tech Review' },
    { url: 'https://venturebeat.com/category/ai/feed/', source: 'VentureBeat AI' },
  ],
  entertainment: [
    { url: 'https://variety.com/feed/', source: 'Variety' },
    { url: 'https://deadline.com/feed/', source: 'Deadline' },
    { url: 'https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml', source: 'BBC Entertainment' },
    { url: 'https://www.theguardian.com/culture/rss', source: 'The Guardian Culture' },
    { url: 'https://www.hollywoodreporter.com/feed/', source: 'Hollywood Reporter' },
    { url: 'http://rss.cnn.com/rss/cnn_showbiz.rss', source: 'CNN Entertainment' },
    { url: 'https://www.nme.com/feed', source: 'NME' },
  ],
  gaming: [
    { url: 'https://feeds.feedburner.com/ign/all', source: 'IGN' },
    { url: 'https://kotaku.com/rss', source: 'Kotaku' },
    { url: 'https://www.polygon.com/rss/index.xml', source: 'Polygon' },
    { url: 'https://www.gamespot.com/feeds/mashup/', source: 'GameSpot' },
  ],
  cricket: [
    { url: 'https://feeds.bbci.co.uk/sport/cricket/rss.xml', source: 'BBC Cricket' },
    { url: 'https://www.espncricinfo.com/rss/content/story/feeds/0.xml', source: 'ESPNcricinfo' },
  ],
  startups: [
    { url: 'https://techcrunch.com/feed/', source: 'TechCrunch' },
    { url: 'https://news.crunchbase.com/feed/', source: 'Crunchbase News' },
    { url: 'https://feeds.feedburner.com/venturebeat/SZYF', source: 'VentureBeat' },
  ],
  space: [
    { url: 'https://spacenews.com/feed/', source: 'SpaceNews' },
    { url: 'https://www.space.com/feeds/all', source: 'Space.com' },
    { url: 'https://www.nasa.gov/rss/dyn/breaking_news.rss', source: 'NASA' },
    { url: 'https://www.universetoday.com/feed', source: 'Universe Today' },
  ],
  crypto: [
    { url: 'https://www.coindesk.com/arc/outboundfeeds/rss/', source: 'CoinDesk' },
    { url: 'https://cointelegraph.com/rss', source: 'CoinTelegraph' },
    { url: 'https://decrypt.co/feed', source: 'Decrypt' },
    { url: 'https://www.theblock.co/rss.xml', source: 'The Block' },
    { url: 'https://bitcoinmagazine.com/feed', source: 'Bitcoin Magazine' },
  ],
};
