import { useState, useEffect, createContext, useContext } from 'react';
import useLocalStorage from './useLocalStorage';

export const LANGUAGES = {
  en: { label: 'English', nativeLabel: 'English', flag: '🇬🇧' },
  hi: { label: 'Hindi', nativeLabel: 'हिन्दी', flag: '🇮🇳' },
  ta: { label: 'Tamil', nativeLabel: 'தமிழ்', flag: '🇮🇳' },
  te: { label: 'Telugu', nativeLabel: 'తెలుగు', flag: '🇮🇳' },
  bn: { label: 'Bengali', nativeLabel: 'বাংলা', flag: '🇮🇳' },
  mr: { label: 'Marathi', nativeLabel: 'मराठी', flag: '🇮🇳' },
};

// UI translations for non-English languages
const UI_STRINGS = {
  en: {
    headlines: "Today's Headlines",
    latest: 'Latest Stories',
    more: 'More Stories',
    localNews: 'Local News',
    viewAll: 'View all',
    search: 'Search news...',
    changeRegion: 'Change region',
    changeLang: 'Language',
    readMore: 'Read more',
    minRead: 'min read',
    bookmarks: 'Bookmarks',
    noResults: 'No results found',
    tryDifferent: 'Try a different search term',
    backHome: 'Back to home',
    searchResults: 'Search results for',
    articlesFound: 'articles found',
    compare: 'Compare',
    feeds: 'Custom Feeds',
    about: 'About',
    subscribe: 'Subscribe',
    newsletter: 'Newsletter',
    daily: 'Daily',
    weekly: 'Weekly',
  },
  hi: {
    headlines: 'आज की सुर्खियाँ',
    latest: 'ताज़ा खबरें',
    more: 'और खबरें',
    localNews: 'स्थानीय समाचार',
    viewAll: 'सभी देखें',
    search: 'समाचार खोजें...',
    changeRegion: 'क्षेत्र बदलें',
    changeLang: 'भाषा',
    readMore: 'और पढ़ें',
    minRead: 'मिनट पढ़ने का समय',
    bookmarks: 'बुकमार्क',
    noResults: 'कोई परिणाम नहीं मिला',
    tryDifferent: 'कोई अन्य शब्द खोजें',
    backHome: 'होम पर वापस जाएँ',
    searchResults: 'खोज परिणाम',
    articlesFound: 'लेख मिले',
    compare: 'तुलना',
    feeds: 'कस्टम फ़ीड',
    about: 'हमारे बारे में',
    subscribe: 'सदस्यता लें',
    newsletter: 'न्यूज़लेटर',
    daily: 'दैनिक',
    weekly: 'साप्ताहिक',
  },
  ta: {
    headlines: 'இன்றைய தலைப்புச் செய்திகள்',
    latest: 'சமீபத்திய செய்திகள்',
    more: 'மேலும் செய்திகள்',
    localNews: 'உள்ளூர் செய்திகள்',
    viewAll: 'அனைத்தும் பார்க்க',
    search: 'செய்திகளைத் தேடு...',
    changeRegion: 'பகுதியை மாற்று',
    changeLang: 'மொழி',
    readMore: 'மேலும் படிக்க',
    minRead: 'நிமிடம் படிக்க',
    bookmarks: 'புக்மார்க்',
    noResults: 'முடிவுகள் இல்லை',
    tryDifferent: 'வேறு சொல்லைத் தேடுங்கள்',
    backHome: 'முகப்பிற்குச் செல்',
    searchResults: 'தேடல் முடிவுகள்',
    articlesFound: 'கட்டுரைகள் கிடைத்தன',
    compare: 'ஒப்பிடு',
    feeds: 'தனிப்பயன் ஊட்டம்',
    about: 'எங்களைப் பற்றி',
    subscribe: 'சந்தா செலுத்து',
    newsletter: 'செய்திமடல்',
    daily: 'தினசரி',
    weekly: 'வாராந்திர',
  },
  te: {
    headlines: 'నేటి ముఖ్యాంశాలు',
    latest: 'తాజా వార్తలు',
    more: 'మరిన్ని వార్తలు',
    localNews: 'స్థానిక వార్తలు',
    viewAll: 'అన్నీ చూడండి',
    search: 'వార్తలు వెతకండి...',
    changeRegion: 'ప్రాంతం మార్చండి',
    changeLang: 'భాష',
    readMore: 'మరింత చదవండి',
    minRead: 'నిమిషాల చదువు',
    bookmarks: 'బుక్‌మార్క్‌లు',
    noResults: 'ఫలితాలు కనుగొనబడలేదు',
    tryDifferent: 'వేరే పదంతో వెతకండి',
    backHome: 'హోమ్‌కి తిరిగి వెళ్ళు',
    searchResults: 'శోధన ఫలితాలు',
    articlesFound: 'వ్యాసాలు కనుగొనబడ్డాయి',
    compare: 'పోల్చండి',
    feeds: 'కస్టమ్ ఫీడ్‌లు',
    about: 'మా గురించి',
    subscribe: 'చందా చేయండి',
    newsletter: 'వార్తాపత్రం',
    daily: 'రోజువారీ',
    weekly: 'వారంవారీ',
  },
  bn: {
    headlines: 'আজকের শিরোনাম',
    latest: 'সাম্প্রতিক খবর',
    more: 'আরও খবর',
    localNews: 'স্থানীয় সংবাদ',
    viewAll: 'সব দেখুন',
    search: 'সংবাদ খুঁজুন...',
    changeRegion: 'অঞ্চল পরিবর্তন',
    changeLang: 'ভাষা',
    readMore: 'আরও পড়ুন',
    minRead: 'মিনিট পড়া',
    bookmarks: 'বুকমার্ক',
    noResults: 'কোনো ফলাফল পাওয়া যায়নি',
    tryDifferent: 'অন্য শব্দ দিয়ে খুঁজুন',
    backHome: 'হোমে ফিরে যান',
    searchResults: 'অনুসন্ধান ফলাফল',
    articlesFound: 'নিবন্ধ পাওয়া গেছে',
    compare: 'তুলনা',
    feeds: 'কাস্টম ফিড',
    about: 'আমাদের সম্পর্কে',
    subscribe: 'সাবস্ক্রাইব',
    newsletter: 'নিউজলেটার',
    daily: 'দৈনিক',
    weekly: 'সাপ্তাহিক',
  },
  mr: {
    headlines: 'आजच्या मथळे',
    latest: 'ताज्या बातम्या',
    more: 'अधिक बातम्या',
    localNews: 'स्थानिक बातम्या',
    viewAll: 'सर्व पहा',
    search: 'बातम्या शोधा...',
    changeRegion: 'प्रदेश बदला',
    changeLang: 'भाषा',
    readMore: 'पुढे वाचा',
    minRead: 'मिनिटे वाचन',
    bookmarks: 'बुकमार्क',
    noResults: 'कोणतेही परिणाम सापडले नाहीत',
    tryDifferent: 'वेगळा शब्द शोधा',
    backHome: 'मुख्यपृष्ठावर परत',
    searchResults: 'शोध परिणाम',
    articlesFound: 'लेख सापडले',
    compare: 'तुलना',
    feeds: 'कस्टम फीड',
    about: 'आमच्याबद्दल',
    subscribe: 'सदस्यता घ्या',
    newsletter: 'वृत्तपत्र',
    daily: 'दैनिक',
    weekly: 'साप्ताहिक',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useLocalStorage('pulsenews-lang', 'en');

  const t = (key) => UI_STRINGS[lang]?.[key] || UI_STRINGS.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, langInfo: LANGUAGES[lang] || LANGUAGES.en }}>
      {children}
    </LanguageContext.Provider>
  );
}

export default function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
