import { useState, useEffect, createContext, useContext } from 'react';
import useLocalStorage from './useLocalStorage';

export const LANGUAGES = {
  en: { label: 'English', nativeLabel: 'English', flag: '🇬🇧' },
  // Indian
  hi: { label: 'Hindi', nativeLabel: 'हिन्दी', flag: '🇮🇳' },
  ta: { label: 'Tamil', nativeLabel: 'தமிழ்', flag: '🇮🇳' },
  te: { label: 'Telugu', nativeLabel: 'తెలుగు', flag: '🇮🇳' },
  bn: { label: 'Bengali', nativeLabel: 'বাংলা', flag: '🇮🇳' },
  mr: { label: 'Marathi', nativeLabel: 'मराठी', flag: '🇮🇳' },
  kn: { label: 'Kannada', nativeLabel: 'ಕನ್ನಡ', flag: '🇮🇳' },
  ml: { label: 'Malayalam', nativeLabel: 'മലയാളം', flag: '🇮🇳' },
  gu: { label: 'Gujarati', nativeLabel: 'ગુજરાતી', flag: '🇮🇳' },
  pa: { label: 'Punjabi', nativeLabel: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  as: { label: 'Assamese', nativeLabel: 'অসমীয়া', flag: '🇮🇳' },
  ur: { label: 'Urdu', nativeLabel: 'اردو', flag: '🇵🇰' },
  // Middle East
  ar: { label: 'Arabic', nativeLabel: 'العربية', flag: '🇸🇦' },
  // European
  fr: { label: 'French', nativeLabel: 'Français', flag: '🇫🇷' },
  de: { label: 'German', nativeLabel: 'Deutsch', flag: '🇩🇪' },
  es: { label: 'Spanish', nativeLabel: 'Español', flag: '🇪🇸' },
  pt: { label: 'Portuguese', nativeLabel: 'Português', flag: '🇧🇷' },
  // Asian
  zh: { label: 'Chinese', nativeLabel: '中文', flag: '🇨🇳' },
  ja: { label: 'Japanese', nativeLabel: '日本語', flag: '🇯🇵' },
  ko: { label: 'Korean', nativeLabel: '한국어', flag: '🇰🇷' },
  // African
  sw: { label: 'Swahili', nativeLabel: 'Kiswahili', flag: '🇰🇪' },
};

// Which languages are available per region
export const REGION_LANGUAGES = {
  india: ['en', 'hi', 'ta', 'te', 'bn', 'mr', 'kn', 'ml', 'gu', 'pa', 'as', 'ur'],
  uk: ['en'],
  us: ['en', 'es'],
  australia: ['en'],
  'middle-east': ['en', 'ar', 'ur'],
  europe: ['en', 'fr', 'de', 'es'],
  africa: ['en', 'fr', 'sw'],
  asia: ['en', 'zh', 'ja', 'ko'],
  latam: ['en', 'es', 'pt'],
};

const UI_STRINGS = {
  en: {
    headlines: "Today's Headlines",
    latest: 'Latest Stories',
    more: 'More Stories',
    localNews: 'Local News',
    viewAll: 'View all',
    search: 'Search news...',
    changeRegion: 'Change region',
    changeLang: 'Language',
    readMore: 'Read more',
    minRead: 'min read',
    bookmarks: 'Bookmarks',
    noResults: 'No results found',
    tryDifferent: 'Try a different search term',
    backHome: 'Back to home',
    searchResults: 'Search results for',
    articlesFound: 'articles found',
    feeds: 'Custom Feeds',
    about: 'About',
    subscribe: 'Subscribe',
    newsletter: 'Newsletter',
    daily: 'Daily',
    weekly: 'Weekly',
    // Categories
    catWorld: 'World', catTechnology: 'Technology', catBusiness: 'Business', catSport: 'Sport',
    catScience: 'Science', catCulture: 'Culture', catEnvironment: 'Environment', catPolitics: 'Politics',
    catAi: 'AI', catEntertainment: 'Entertainment', catGaming: 'Gaming', catCricket: 'Cricket',
    catStartups: 'Startups', catSpace: 'Space', catCrypto: 'Crypto', catTopStories: 'Top Stories',
    // Navigation
    regions: 'Regions', archive: 'Archive',
    // Region page
    region: 'Region', yourRegion: 'Your region', setAsRegion: 'Set as my region',
    latestFrom: 'Latest news from', latestFromShort: 'Latest from',
    noNewsAvailable: 'No news available',
    // Explore
    exploreByRegion: 'Explore by Region', newsFromWorld: 'News from around the world', explore: 'Explore',
  },
  hi: {
    headlines: 'आज की सुर्खियाँ',
    latest: 'ताज़ा खबरें',
    more: 'और खबरें',
    localNews: 'स्थानीय समाचार',
    viewAll: 'सभी देखें',
    search: 'समाचार खोजें...',
    changeRegion: 'क्षेत्र बदलें',
    changeLang: 'भाषा',
    readMore: 'और पढ़ें',
    minRead: 'मिनट पढ़ने का समय',
    bookmarks: 'बुकमार्क',
    noResults: 'कोई परिणाम नहीं मिला',
    tryDifferent: 'कोई अन्य शब्द खोजें',
    backHome: 'होम पर वापस जाएँ',
    searchResults: 'खोज परिणाम',
    articlesFound: 'लेख मिले',
    feeds: 'कस्टम फ़ीड',
    about: 'हमारे बारे में',
    subscribe: 'सदस्यता लें',
    newsletter: 'न्यूज़लेटर',
    daily: 'दैनिक',
    weekly: 'साप्ताहिक',
    catWorld: 'दुनिया', catTechnology: 'प्रौद्योगिकी', catBusiness: 'व्यापार', catSport: 'खेल',
    catScience: 'विज्ञान', catCulture: 'संस्कृति', catEnvironment: 'पर्यावरण', catPolitics: 'राजनीति',
    catAi: 'AI', catEntertainment: 'मनोरंजन', catGaming: 'गेमिंग', catCricket: 'क्रिकेट',
    catStartups: 'स्टार्टअप', catSpace: 'अंतरिक्ष', catCrypto: 'क्रिप्टो', catTopStories: 'मुख्य समाचार',
    regions: 'क्षेत्र', archive: 'संग्रह',
    region: 'क्षेत्र', yourRegion: 'आपका क्षेत्र', setAsRegion: 'मेरा क्षेत्र सेट करें',
    latestFrom: 'से ताज़ा समाचार', latestFromShort: 'ताज़ा खबरें',
    noNewsAvailable: 'कोई समाचार उपलब्ध नहीं',
    exploreByRegion: 'क्षेत्र अनुसार खोजें', newsFromWorld: 'दुनिया भर से समाचार', explore: 'एक्सप्लोर',
  },
  ta: {
    headlines: 'இன்றைய தலைப்புச் செய்திகள்',
    latest: 'சமீபத்திய செய்திகள்',
    more: 'மேலும் செய்திகள்',
    localNews: 'உள்ளூர் செய்திகள்',
    viewAll: 'அனைத்தும் பார்க்க',
    search: 'செய்திகளைத் தேடு...',
    changeRegion: 'பகுதியை மாற்று',
    changeLang: 'மொழி',
    readMore: 'மேலும் படிக்க',
    minRead: 'நிமிடம் படிக்க',
    bookmarks: 'புக்மார்க்',
    noResults: 'முடிவுகள் இல்லை',
    tryDifferent: 'வேறு சொல்லைத் தேடுங்கள்',
    backHome: 'முகப்பிற்குச் செல்',
    searchResults: 'தேடல் முடிவுகள்',
    articlesFound: 'கட்டுரைகள் கிடைத்தன',
    feeds: 'தனிப்பயன் ஊட்டம்',
    about: 'எங்களைப் பற்றி',
    subscribe: 'சந்தா செலுத்து',
    newsletter: 'செய்திமடல்',
    daily: 'தினசரி',
    weekly: 'வாராந்திர',
    catWorld: 'உலகம்', catTechnology: 'தொழில்நுட்பம்', catBusiness: 'வணிகம்', catSport: 'விளையாட்டு',
    catScience: 'அறிவியல்', catCulture: 'கலாச்சாரம்', catEnvironment: 'சுற்றுச்சூழல்', catPolitics: 'அரசியல்',
    catAi: 'AI', catEntertainment: 'பொழுதுபோக்கு', catGaming: 'கேமிங்', catCricket: 'கிரிக்கெட்',
    catStartups: 'ஸ்டார்ட்அப்', catSpace: 'விண்வெளி', catCrypto: 'கிரிப்டோ', catTopStories: 'முக்கிய செய்திகள்',
    regions: 'பகுதிகள்', archive: 'காப்பகம்',
    region: 'பகுதி', yourRegion: 'உங்கள் பகுதி', setAsRegion: 'என் பகுதியாக அமை',
    latestFrom: 'இலிருந்து சமீபத்திய செய்திகள்', latestFromShort: 'சமீபத்திய',
    noNewsAvailable: 'செய்திகள் இல்லை',
    exploreByRegion: 'பகுதி வாரியாக ஆராய', newsFromWorld: 'உலகம் முழுவதும் செய்திகள்', explore: 'ஆராய',
  },
  te: {
    headlines: 'నేటి ముఖ్యాంశాలు',
    latest: 'తాజా వార్తలు',
    more: 'మరిన్ని వార్తలు',
    localNews: 'స్థానిక వార్తలు',
    viewAll: 'అన్నీ చూడండి',
    search: 'వార్తలు వెతకండి...',
    changeRegion: 'ప్రాంతం మార్చండి',
    changeLang: 'భాష',
    readMore: 'మరింత చదవండి',
    minRead: 'నిమిషాల చదువు',
    bookmarks: 'బుక్‌మార్క్‌లు',
    noResults: 'ఫలితాలు కనుగొనబడలేదు',
    tryDifferent: 'వేరే పదంతో వెతకండి',
    backHome: 'హోమ్‌కి తిరిగి వెళ్ళు',
    searchResults: 'శోధన ఫలితాలు',
    articlesFound: 'వ్యాసాలు కనుగొనబడ్డాయి',
    feeds: 'కస్టమ్ ఫీడ్‌లు',
    about: 'మా గురించి',
    subscribe: 'చందా చేయండి',
    newsletter: 'వార్తాపత్రం',
    daily: 'రోజువారీ',
    weekly: 'వారంవారీ',
    catWorld: 'ప్రపంచం', catTechnology: 'సాంకేతికత', catBusiness: 'వ్యాపారం', catSport: 'క్రీడ',
    catScience: 'సైన్స్', catCulture: 'సంస్కృతి', catEnvironment: 'పర్యావరణం', catPolitics: 'రాజకీయాలు',
    catAi: 'AI', catEntertainment: 'వినోదం', catGaming: 'గేమింగ్', catCricket: 'క్రికెట్',
    catStartups: 'స్టార్టప్‌లు', catSpace: 'అంతరిక్షం', catCrypto: 'క్రిప్టో', catTopStories: 'ప్రధాన వార్తలు',
    regions: 'ప్రాంతాలు', archive: 'ఆర్కైవ్',
    region: 'ప్రాంతం', yourRegion: 'మీ ప్రాంతం', setAsRegion: 'నా ప్రాంతంగా సెట్ చేయండి',
    latestFrom: 'నుండి తాజా వార్తలు', latestFromShort: 'తాజా',
    noNewsAvailable: 'వార్తలు అందుబాటులో లేవు',
    exploreByRegion: 'ప్రాంతం వారీగా అన్వేషించండి', newsFromWorld: 'ప్రపంచం నలుమూలల నుండి వార్తలు', explore: 'అన్వేషించు',
  },
  bn: {
    headlines: 'আজকের শিরোনাম',
    latest: 'সাম্প্রতিক খবর',
    more: 'আরও খবর',
    localNews: 'স্থানীয় সংবাদ',
    viewAll: 'সব দেখুন',
    search: 'সংবাদ খুঁজুন...',
    changeRegion: 'অঞ্চল পরিবর্তন',
    changeLang: 'ভাষা',
    readMore: 'আরও পড়ুন',
    minRead: 'মিনিট পড়া',
    bookmarks: 'বুকমার্ক',
    noResults: 'কোনো ফলাফল পাওয়া যায়নি',
    tryDifferent: 'অন্য শব্দ দিয়ে খুঁজুন',
    backHome: 'হোমে ফিরে যান',
    searchResults: 'অনুসন্ধান ফলাফল',
    articlesFound: 'নিবন্ধ পাওয়া গেছে',
    feeds: 'কাস্টম ফিড',
    about: 'আমাদের সম্পর্কে',
    subscribe: 'সাবস্ক্রাইব',
    newsletter: 'নিউজলেটার',
    daily: 'দৈনিক',
    weekly: 'সাপ্তাহিক',
    catWorld: 'বিশ্ব', catTechnology: 'প্রযুক্তি', catBusiness: 'ব্যবসা', catSport: 'খেলা',
    catScience: 'বিজ্ঞান', catCulture: 'সংস্কৃতি', catEnvironment: 'পরিবেশ', catPolitics: 'রাজনীতি',
    catAi: 'AI', catEntertainment: 'বিনোদন', catGaming: 'গেমিং', catCricket: 'ক্রিকেট',
    catStartups: 'স্টার্টআপ', catSpace: 'মহাকাশ', catCrypto: 'ক্রিপ্টো', catTopStories: 'প্রধান সংবাদ',
    regions: 'অঞ্চল', archive: 'আর্কাইভ',
    region: 'অঞ্চল', yourRegion: 'আপনার অঞ্চল', setAsRegion: 'আমার অঞ্চল সেট করুন',
    latestFrom: 'থেকে সাম্প্রতিক সংবাদ', latestFromShort: 'সাম্প্রতিক',
    noNewsAvailable: 'কোনো সংবাদ নেই',
    exploreByRegion: 'অঞ্চল অনুসারে অন্বেষণ', newsFromWorld: 'বিশ্বজুড়ে সংবাদ', explore: 'অন্বেষণ',
  },
  mr: {
    headlines: 'आजच्या मथळे',
    latest: 'ताज्या बातम्या',
    more: 'अधिक बातम्या',
    localNews: 'स्थानिक बातम्या',
    viewAll: 'सर्व पहा',
    search: 'बातम्या शोधा...',
    changeRegion: 'प्रदेश बदला',
    changeLang: 'भाषा',
    readMore: 'पुढे वाचा',
    minRead: 'मिनिटे वाचन',
    bookmarks: 'बुकमार्क',
    noResults: 'कोणतेही परिणाम सापडले नाहीत',
    tryDifferent: 'वेगळा शब्द शोधा',
    backHome: 'मुख्यपृष्ठावर परत',
    searchResults: 'शोध परिणाम',
    articlesFound: 'लेख सापडले',
    feeds: 'कस्टम फीड',
    about: 'आमच्याबद्दल',
    subscribe: 'सदस्यता घ्या',
    newsletter: 'वृत्तपत्र',
    daily: 'दैनिक',
    weekly: 'साप्ताहिक',
    catWorld: 'जग', catTechnology: 'तंत्रज्ञान', catBusiness: 'व्यवसाय', catSport: 'खेळ',
    catScience: 'विज्ञान', catCulture: 'संस्कृती', catEnvironment: 'पर्यावरण', catPolitics: 'राजकारण',
    catAi: 'AI', catEntertainment: 'मनोरंजन', catGaming: 'गेमिंग', catCricket: 'क्रिकेट',
    catStartups: 'स्टार्टअप', catSpace: 'अंतराळ', catCrypto: 'क्रिप्टो', catTopStories: 'मुख्य बातम्या',
    regions: 'प्रदेश', archive: 'संग्रह',
    region: 'प्रदेश', yourRegion: 'तुमचा प्रदेश', setAsRegion: 'माझा प्रदेश म्हणून सेट करा',
    latestFrom: 'कडून ताज्या बातम्या', latestFromShort: 'ताज्या',
    noNewsAvailable: 'बातम्या उपलब्ध नाहीत',
    exploreByRegion: 'प्रदेशानुसार शोधा', newsFromWorld: 'जगभरातील बातम्या', explore: 'शोधा',
  },
  ur: {
    headlines: 'آج کی سرخیاں',
    latest: 'تازہ خبریں',
    more: 'مزید خبریں',
    localNews: 'مقامی خبریں',
    viewAll: 'سب دیکھیں',
    search: 'خبریں تلاش کریں...',
    changeRegion: 'علاقہ تبدیل کریں',
    changeLang: 'زبان',
    readMore: 'مزید پڑھیں',
    minRead: 'منٹ پڑھنے کا وقت',
    bookmarks: 'بک مارکس',
    noResults: 'کوئی نتیجہ نہیں ملا',
    tryDifferent: 'کوئی اور لفظ تلاش کریں',
    backHome: 'ہوم پر واپس جائیں',
    searchResults: 'تلاش کے نتائج',
    articlesFound: 'مضامین ملے',
    feeds: 'کسٹم فیڈز',
    about: 'ہمارے بارے میں',
    subscribe: 'رکنیت',
    newsletter: 'نیوز لیٹر',
    daily: 'روزانہ',
    weekly: 'ہفتہ وار',
    catWorld: 'دنیا', catTechnology: 'ٹیکنالوجی', catBusiness: 'کاروبار', catSport: 'کھیل',
    catScience: 'سائنس', catCulture: 'ثقافت', catEnvironment: 'ماحولیات', catPolitics: 'سیاست',
    catAi: 'AI', catEntertainment: 'تفریح', catGaming: 'گیمنگ', catCricket: 'کرکٹ',
    catStartups: 'اسٹارٹ اپ', catSpace: 'خلا', catCrypto: 'کرپٹو', catTopStories: 'اہم خبریں',
    regions: 'علاقے', archive: 'محفوظات',
    region: 'علاقہ', yourRegion: 'آپ کا علاقہ', setAsRegion: 'میرا علاقہ مقرر کریں',
    latestFrom: 'سے تازہ خبریں', latestFromShort: 'تازہ ترین',
    noNewsAvailable: 'کوئی خبر دستیاب نہیں',
    exploreByRegion: 'علاقے کے مطابق دریافت کریں', newsFromWorld: 'دنیا بھر سے خبریں', explore: 'دریافت کریں',
  },
  ar: {
    headlines: 'عناوين اليوم',
    latest: 'آخر الأخبار',
    more: 'المزيد من الأخبار',
    localNews: 'الأخبار المحلية',
    viewAll: 'عرض الكل',
    search: 'البحث في الأخبار...',
    changeRegion: 'تغيير المنطقة',
    changeLang: 'اللغة',
    readMore: 'اقرأ المزيد',
    minRead: 'دقائق للقراءة',
    bookmarks: 'المفضلة',
    noResults: 'لم يتم العثور على نتائج',
    tryDifferent: 'جرب كلمة بحث مختلفة',
    backHome: 'العودة إلى الرئيسية',
    searchResults: 'نتائج البحث',
    articlesFound: 'مقالات',
    feeds: 'خلاصات مخصصة',
    about: 'حول',
    subscribe: 'اشتراك',
    newsletter: 'النشرة الإخبارية',
    daily: 'يومي',
    weekly: 'أسبوعي',
    catWorld: 'العالم', catTechnology: 'التكنولوجيا', catBusiness: 'الأعمال', catSport: 'الرياضة',
    catScience: 'العلوم', catCulture: 'الثقافة', catEnvironment: 'البيئة', catPolitics: 'السياسة',
    catAi: 'AI', catEntertainment: 'الترفيه', catGaming: 'الألعاب', catCricket: 'الكريكيت',
    catStartups: 'الشركات الناشئة', catSpace: 'الفضاء', catCrypto: 'العملات الرقمية', catTopStories: 'أهم الأخبار',
    regions: 'المناطق', archive: 'الأرشيف',
    region: 'المنطقة', yourRegion: 'منطقتك', setAsRegion: 'تعيين كمنطقتي',
    latestFrom: 'آخر الأخبار من', latestFromShort: 'الأحدث من',
    noNewsAvailable: 'لا توجد أخبار',
    exploreByRegion: 'استكشاف حسب المنطقة', newsFromWorld: 'أخبار من حول العالم', explore: 'استكشاف',
  },
  fr: {
    headlines: 'Titres du jour',
    latest: 'Dernières nouvelles',
    more: "Plus d'articles",
    localNews: 'Nouvelles locales',
    viewAll: 'Voir tout',
    search: 'Rechercher...',
    changeRegion: 'Changer de région',
    changeLang: 'Langue',
    readMore: 'Lire la suite',
    minRead: 'min de lecture',
    bookmarks: 'Favoris',
    noResults: 'Aucun résultat',
    tryDifferent: 'Essayez un autre terme',
    backHome: "Retour à l'accueil",
    searchResults: 'Résultats pour',
    articlesFound: 'articles trouvés',
    feeds: 'Flux personnalisés',
    about: 'À propos',
    subscribe: "S'abonner",
    newsletter: 'Newsletter',
    daily: 'Quotidien',
    weekly: 'Hebdomadaire',
    catWorld: 'Monde', catTechnology: 'Technologie', catBusiness: 'Affaires', catSport: 'Sport',
    catScience: 'Sciences', catCulture: 'Culture', catEnvironment: 'Environnement', catPolitics: 'Politique',
    catAi: 'IA', catEntertainment: 'Divertissement', catGaming: 'Jeux vidéo', catCricket: 'Cricket',
    catStartups: 'Startups', catSpace: 'Espace', catCrypto: 'Crypto', catTopStories: 'À la une',
    regions: 'Régions', archive: 'Archives',
    region: 'Région', yourRegion: 'Votre région', setAsRegion: 'Définir comme ma région',
    latestFrom: 'Dernières nouvelles de', latestFromShort: 'Dernières de',
    noNewsAvailable: 'Aucune actualité disponible',
    exploreByRegion: 'Explorer par région', newsFromWorld: 'Actualités du monde entier', explore: 'Explorer',
  },
  de: {
    headlines: 'Schlagzeilen',
    latest: 'Neueste Nachrichten',
    more: 'Weitere Nachrichten',
    localNews: 'Lokale Nachrichten',
    viewAll: 'Alle anzeigen',
    search: 'Nachrichten suchen...',
    changeRegion: 'Region ändern',
    changeLang: 'Sprache',
    readMore: 'Weiterlesen',
    minRead: 'Min. Lesezeit',
    bookmarks: 'Lesezeichen',
    noResults: 'Keine Ergebnisse',
    tryDifferent: 'Versuchen Sie einen anderen Begriff',
    backHome: 'Zurück zur Startseite',
    searchResults: 'Suchergebnisse für',
    articlesFound: 'Artikel gefunden',
    feeds: 'Benutzerdefinierte Feeds',
    about: 'Über uns',
    subscribe: 'Abonnieren',
    newsletter: 'Newsletter',
    daily: 'Täglich',
    weekly: 'Wöchentlich',
    catWorld: 'Welt', catTechnology: 'Technologie', catBusiness: 'Wirtschaft', catSport: 'Sport',
    catScience: 'Wissenschaft', catCulture: 'Kultur', catEnvironment: 'Umwelt', catPolitics: 'Politik',
    catAi: 'KI', catEntertainment: 'Unterhaltung', catGaming: 'Gaming', catCricket: 'Cricket',
    catStartups: 'Startups', catSpace: 'Weltraum', catCrypto: 'Krypto', catTopStories: 'Top-Nachrichten',
    regions: 'Regionen', archive: 'Archiv',
    region: 'Region', yourRegion: 'Ihre Region', setAsRegion: 'Als meine Region festlegen',
    latestFrom: 'Neueste Nachrichten aus', latestFromShort: 'Neueste aus',
    noNewsAvailable: 'Keine Nachrichten verfügbar',
    exploreByRegion: 'Nach Region erkunden', newsFromWorld: 'Nachrichten aus aller Welt', explore: 'Erkunden',
  },
  es: {
    headlines: 'Titulares de hoy',
    latest: 'Últimas noticias',
    more: 'Más noticias',
    localNews: 'Noticias locales',
    viewAll: 'Ver todo',
    search: 'Buscar noticias...',
    changeRegion: 'Cambiar región',
    changeLang: 'Idioma',
    readMore: 'Leer más',
    minRead: 'min de lectura',
    bookmarks: 'Marcadores',
    noResults: 'Sin resultados',
    tryDifferent: 'Intenta otro término',
    backHome: 'Volver al inicio',
    searchResults: 'Resultados para',
    articlesFound: 'artículos encontrados',
    feeds: 'Feeds personalizados',
    about: 'Acerca de',
    subscribe: 'Suscribirse',
    newsletter: 'Boletín',
    daily: 'Diario',
    weekly: 'Semanal',
    catWorld: 'Mundo', catTechnology: 'Tecnología', catBusiness: 'Negocios', catSport: 'Deportes',
    catScience: 'Ciencia', catCulture: 'Cultura', catEnvironment: 'Medio ambiente', catPolitics: 'Política',
    catAi: 'IA', catEntertainment: 'Entretenimiento', catGaming: 'Videojuegos', catCricket: 'Críquet',
    catStartups: 'Startups', catSpace: 'Espacio', catCrypto: 'Cripto', catTopStories: 'Principales',
    regions: 'Regiones', archive: 'Archivo',
    region: 'Región', yourRegion: 'Tu región', setAsRegion: 'Establecer como mi región',
    latestFrom: 'Últimas noticias de', latestFromShort: 'Últimas de',
    noNewsAvailable: 'No hay noticias disponibles',
    exploreByRegion: 'Explorar por región', newsFromWorld: 'Noticias de todo el mundo', explore: 'Explorar',
  },
  pt: {
    headlines: 'Manchetes de hoje',
    latest: 'Últimas notícias',
    more: 'Mais notícias',
    localNews: 'Notícias locais',
    viewAll: 'Ver tudo',
    search: 'Buscar notícias...',
    changeRegion: 'Mudar região',
    changeLang: 'Idioma',
    readMore: 'Leia mais',
    minRead: 'min de leitura',
    bookmarks: 'Favoritos',
    noResults: 'Nenhum resultado',
    tryDifferent: 'Tente outro termo',
    backHome: 'Voltar ao início',
    searchResults: 'Resultados para',
    articlesFound: 'artigos encontrados',
    feeds: 'Feeds personalizados',
    about: 'Sobre',
    subscribe: 'Inscrever-se',
    newsletter: 'Newsletter',
    daily: 'Diário',
    weekly: 'Semanal',
    catWorld: 'Mundo', catTechnology: 'Tecnologia', catBusiness: 'Negócios', catSport: 'Esportes',
    catScience: 'Ciência', catCulture: 'Cultura', catEnvironment: 'Meio ambiente', catPolitics: 'Política',
    catAi: 'IA', catEntertainment: 'Entretenimento', catGaming: 'Jogos', catCricket: 'Críquete',
    catStartups: 'Startups', catSpace: 'Espaço', catCrypto: 'Cripto', catTopStories: 'Destaques',
    regions: 'Regiões', archive: 'Arquivo',
    region: 'Região', yourRegion: 'Sua região', setAsRegion: 'Definir como minha região',
    latestFrom: 'Últimas notícias de', latestFromShort: 'Últimas de',
    noNewsAvailable: 'Nenhuma notícia disponível',
    exploreByRegion: 'Explorar por região', newsFromWorld: 'Notícias de todo o mundo', explore: 'Explorar',
  },
  zh: {
    headlines: '今日头条',
    latest: '最新新闻',
    more: '更多新闻',
    localNews: '本地新闻',
    viewAll: '查看全部',
    search: '搜索新闻...',
    changeRegion: '更改地区',
    changeLang: '语言',
    readMore: '阅读更多',
    minRead: '分钟阅读',
    bookmarks: '收藏',
    noResults: '没有找到结果',
    tryDifferent: '尝试其他搜索词',
    backHome: '返回首页',
    searchResults: '搜索结果',
    articlesFound: '篇文章',
    feeds: '自定义源',
    about: '关于',
    subscribe: '订阅',
    newsletter: '新闻简报',
    daily: '每日',
    weekly: '每周',
    catWorld: '世界', catTechnology: '科技', catBusiness: '商业', catSport: '体育',
    catScience: '科学', catCulture: '文化', catEnvironment: '环境', catPolitics: '政治',
    catAi: 'AI', catEntertainment: '娱乐', catGaming: '游戏', catCricket: '板球',
    catStartups: '创业', catSpace: '太空', catCrypto: '加密货币', catTopStories: '头条新闻',
    regions: '地区', archive: '存档',
    region: '地区', yourRegion: '您的地区', setAsRegion: '设为我的地区',
    latestFrom: '来自的最新新闻', latestFromShort: '最新',
    noNewsAvailable: '暂无新闻',
    exploreByRegion: '按地区浏览', newsFromWorld: '全球新闻', explore: '探索',
  },
  ja: {
    headlines: '今日のヘッドライン',
    latest: '最新ニュース',
    more: 'もっと見る',
    localNews: 'ローカルニュース',
    viewAll: 'すべて見る',
    search: 'ニュースを検索...',
    changeRegion: '地域を変更',
    changeLang: '言語',
    readMore: '続きを読む',
    minRead: '分で読める',
    bookmarks: 'ブックマーク',
    noResults: '結果が見つかりません',
    tryDifferent: '別のキーワードで検索',
    backHome: 'ホームに戻る',
    searchResults: '検索結果',
    articlesFound: '件の記事',
    feeds: 'カスタムフィード',
    about: '概要',
    subscribe: '購読',
    newsletter: 'ニュースレター',
    daily: '日刊',
    weekly: '週刊',
    catWorld: '世界', catTechnology: 'テクノロジー', catBusiness: 'ビジネス', catSport: 'スポーツ',
    catScience: '科学', catCulture: '文化', catEnvironment: '環境', catPolitics: '政治',
    catAi: 'AI', catEntertainment: 'エンタメ', catGaming: 'ゲーム', catCricket: 'クリケット',
    catStartups: 'スタートアップ', catSpace: '宇宙', catCrypto: '暗号通貨', catTopStories: 'トップニュース',
    regions: '地域', archive: 'アーカイブ',
    region: '地域', yourRegion: 'あなたの地域', setAsRegion: '私の地域に設定',
    latestFrom: 'からの最新ニュース', latestFromShort: '最新',
    noNewsAvailable: 'ニュースはありません',
    exploreByRegion: '地域別に探す', newsFromWorld: '世界中のニュース', explore: '探索',
  },
  ko: {
    headlines: '오늘의 헤드라인',
    latest: '최신 뉴스',
    more: '더 보기',
    localNews: '지역 뉴스',
    viewAll: '모두 보기',
    search: '뉴스 검색...',
    changeRegion: '지역 변경',
    changeLang: '언어',
    readMore: '더 읽기',
    minRead: '분 읽기',
    bookmarks: '북마크',
    noResults: '결과 없음',
    tryDifferent: '다른 검색어를 시도하세요',
    backHome: '홈으로 돌아가기',
    searchResults: '검색 결과',
    articlesFound: '개의 기사',
    feeds: '맞춤 피드',
    about: '소개',
    subscribe: '구독',
    newsletter: '뉴스레터',
    daily: '일간',
    weekly: '주간',
    catWorld: '세계', catTechnology: '기술', catBusiness: '경제', catSport: '스포츠',
    catScience: '과학', catCulture: '문화', catEnvironment: '환경', catPolitics: '정치',
    catAi: 'AI', catEntertainment: '연예', catGaming: '게임', catCricket: '크리켓',
    catStartups: '스타트업', catSpace: '우주', catCrypto: '암호화폐', catTopStories: '주요 뉴스',
    regions: '지역', archive: '보관함',
    region: '지역', yourRegion: '내 지역', setAsRegion: '내 지역으로 설정',
    latestFrom: '최신 뉴스', latestFromShort: '최신',
    noNewsAvailable: '뉴스가 없습니다',
    exploreByRegion: '지역별 탐색', newsFromWorld: '전 세계 뉴스', explore: '탐색',
  },
  sw: {
    headlines: 'Vichwa vya Habari',
    latest: 'Habari za Hivi Karibuni',
    more: 'Habari Zaidi',
    localNews: 'Habari za Mtaa',
    viewAll: 'Tazama Zote',
    search: 'Tafuta habari...',
    changeRegion: 'Badilisha eneo',
    changeLang: 'Lugha',
    readMore: 'Soma zaidi',
    minRead: 'dakika za kusoma',
    bookmarks: 'Alamisho',
    noResults: 'Hakuna matokeo',
    tryDifferent: 'Jaribu neno lingine',
    backHome: 'Rudi nyumbani',
    searchResults: 'Matokeo ya utafutaji',
    articlesFound: 'makala zimepatikana',
    feeds: 'Vipasho Maalum',
    about: 'Kuhusu',
    subscribe: 'Jiandikishe',
    newsletter: 'Jarida',
    daily: 'Kila siku',
    weekly: 'Kila wiki',
    catWorld: 'Dunia', catTechnology: 'Teknolojia', catBusiness: 'Biashara', catSport: 'Michezo',
    catScience: 'Sayansi', catCulture: 'Utamaduni', catEnvironment: 'Mazingira', catPolitics: 'Siasa',
    catAi: 'AI', catEntertainment: 'Burudani', catGaming: 'Michezo ya Kompyuta', catCricket: 'Kriketi',
    catStartups: 'Biashara Mpya', catSpace: 'Angani', catCrypto: 'Kripto', catTopStories: 'Habari Kuu',
    regions: 'Maeneo', archive: 'Kumbukumbu',
    region: 'Eneo', yourRegion: 'Eneo lako', setAsRegion: 'Weka kama eneo langu',
    latestFrom: 'Habari za hivi karibuni kutoka', latestFromShort: 'Za hivi karibuni',
    noNewsAvailable: 'Hakuna habari',
    exploreByRegion: 'Chunguza kwa eneo', newsFromWorld: 'Habari kutoka ulimwenguni', explore: 'Chunguza',
  },
};

// Map category key to translation key
const CAT_KEY_MAP = {
  world: 'catWorld', technology: 'catTechnology', business: 'catBusiness', sport: 'catSport',
  science: 'catScience', culture: 'catCulture', environment: 'catEnvironment', politics: 'catPolitics',
  ai: 'catAi', entertainment: 'catEntertainment', gaming: 'catGaming', cricket: 'catCricket',
  startups: 'catStartups', space: 'catSpace', crypto: 'catCrypto',
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useLocalStorage('pulsenews-lang', 'en');

  const t = (key) => UI_STRINGS[lang]?.[key] || UI_STRINGS.en[key] || key;
  const tCat = (catKey) => t(CAT_KEY_MAP[catKey] || catKey);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, tCat, langInfo: LANGUAGES[lang] || LANGUAGES.en }}>
      {children}
    </LanguageContext.Provider>
  );
}

export default function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
