import { useState, useEffect, createContext, useContext } from 'react';
import useLocalStorage from './useLocalStorage';

export const LANGUAGES = {
  en: { label: 'English', nativeLabel: 'English', flag: '🇬🇧' },
  // Indian
  hi: { label: 'Hindi', nativeLabel: 'हिन्दी', flag: '🇮🇳' },
  ta: { label: 'Tamil', nativeLabel: 'தமிழ்', flag: '🇮🇳' },
  te: { label: 'Telugu', nativeLabel: 'తెలుగు', flag: '🇮🇳' },
  bn: { label: 'Bengali', nativeLabel: 'বাংলা', flag: '🇮🇳' },
  mr: { label: 'Marathi', nativeLabel: 'मराठी', flag: '🇮🇳' },
  ur: { label: 'Urdu', nativeLabel: 'اردو', flag: '🇵🇰' },
  // Middle East
  ar: { label: 'Arabic', nativeLabel: 'العربية', flag: '🇸🇦' },
  // European
  fr: { label: 'French', nativeLabel: 'Français', flag: '🇫🇷' },
  de: { label: 'German', nativeLabel: 'Deutsch', flag: '🇩🇪' },
  es: { label: 'Spanish', nativeLabel: 'Español', flag: '🇪🇸' },
  pt: { label: 'Portuguese', nativeLabel: 'Português', flag: '🇧🇷' },
  // Asian
  zh: { label: 'Chinese', nativeLabel: '中文', flag: '🇨🇳' },
  ja: { label: 'Japanese', nativeLabel: '日本語', flag: '🇯🇵' },
  ko: { label: 'Korean', nativeLabel: '한국어', flag: '🇰🇷' },
  // African
  sw: { label: 'Swahili', nativeLabel: 'Kiswahili', flag: '🇰🇪' },
};

// Which languages are available per region
export const REGION_LANGUAGES = {
  india: ['en', 'hi', 'ta', 'te', 'bn', 'mr', 'ur'],
  uk: ['en'],
  us: ['en', 'es'],
  australia: ['en'],
  'middle-east': ['en', 'ar', 'ur'],
  europe: ['en', 'fr', 'de', 'es'],
  africa: ['en', 'fr', 'sw'],
  asia: ['en', 'zh', 'ja', 'ko'],
  latam: ['en', 'es', 'pt'],
};

const UI_STRINGS = {
  en: {
    headlines: "Today's Headlines",
    latest: 'Latest Stories',
    more: 'More Stories',
    localNews: 'Local News',
    viewAll: 'View all',
    search: 'Search news...',
    changeRegion: 'Change region',
    changeLang: 'Language',
    readMore: 'Read more',
    minRead: 'min read',
    bookmarks: 'Bookmarks',
    noResults: 'No results found',
    tryDifferent: 'Try a different search term',
    backHome: 'Back to home',
    searchResults: 'Search results for',
    articlesFound: 'articles found',
    feeds: 'Custom Feeds',
    about: 'About',
    subscribe: 'Subscribe',
    newsletter: 'Newsletter',
    daily: 'Daily',
    weekly: 'Weekly',
  },
  hi: {
    headlines: 'आज की सुर्खियाँ',
    latest: 'ताज़ा खबरें',
    more: 'और खबरें',
    localNews: 'स्थानीय समाचार',
    viewAll: 'सभी देखें',
    search: 'समाचार खोजें...',
    changeRegion: 'क्षेत्र बदलें',
    changeLang: 'भाषा',
    readMore: 'और पढ़ें',
    minRead: 'मिनट पढ़ने का समय',
    bookmarks: 'बुकमार्क',
    noResults: 'कोई परिणाम नहीं मिला',
    tryDifferent: 'कोई अन्य शब्द खोजें',
    backHome: 'होम पर वापस जाएँ',
    searchResults: 'खोज परिणाम',
    articlesFound: 'लेख मिले',
    feeds: 'कस्टम फ़ीड',
    about: 'हमारे बारे में',
    subscribe: 'सदस्यता लें',
    newsletter: 'न्यूज़लेटर',
    daily: 'दैनिक',
    weekly: 'साप्ताहिक',
  },
  ta: {
    headlines: 'இன்றைய தலைப்புச் செய்திகள்',
    latest: 'சமீபத்திய செய்திகள்',
    more: 'மேலும் செய்திகள்',
    localNews: 'உள்ளூர் செய்திகள்',
    viewAll: 'அனைத்தும் பார்க்க',
    search: 'செய்திகளைத் தேடு...',
    changeRegion: 'பகுதியை மாற்று',
    changeLang: 'மொழி',
    readMore: 'மேலும் படிக்க',
    minRead: 'நிமிடம் படிக்க',
    bookmarks: 'புக்மார்க்',
    noResults: 'முடிவுகள் இல்லை',
    tryDifferent: 'வேறு சொல்லைத் தேடுங்கள்',
    backHome: 'முகப்பிற்குச் செல்',
    searchResults: 'தேடல் முடிவுகள்',
    articlesFound: 'கட்டுரைகள் கிடைத்தன',
    feeds: 'தனிப்பயன் ஊட்டம்',
    about: 'எங்களைப் பற்றி',
    subscribe: 'சந்தா செலுத்து',
    newsletter: 'செய்திமடல்',
    daily: 'தினசரி',
    weekly: 'வாராந்திர',
  },
  te: {
    headlines: 'నేటి ముఖ్యాంశాలు',
    latest: 'తాజా వార్తలు',
    more: 'మరిన్ని వార్తలు',
    localNews: 'స్థానిక వార్తలు',
    viewAll: 'అన్నీ చూడండి',
    search: 'వార్తలు వెతకండి...',
    changeRegion: 'ప్రాంతం మార్చండి',
    changeLang: 'భాష',
    readMore: 'మరింత చదవండి',
    minRead: 'నిమిషాల చదువు',
    bookmarks: 'బుక్‌మార్క్‌లు',
    noResults: 'ఫలితాలు కనుగొనబడలేదు',
    tryDifferent: 'వేరే పదంతో వెతకండి',
    backHome: 'హోమ్‌కి తిరిగి వెళ్ళు',
    searchResults: 'శోధన ఫలితాలు',
    articlesFound: 'వ్యాసాలు కనుగొనబడ్డాయి',
    feeds: 'కస్టమ్ ఫీడ్‌లు',
    about: 'మా గురించి',
    subscribe: 'చందా చేయండి',
    newsletter: 'వార్తాపత్రం',
    daily: 'రోజువారీ',
    weekly: 'వారంవారీ',
  },
  bn: {
    headlines: 'আজকের শিরোনাম',
    latest: 'সাম্প্রতিক খবর',
    more: 'আরও খবর',
    localNews: 'স্থানীয় সংবাদ',
    viewAll: 'সব দেখুন',
    search: 'সংবাদ খুঁজুন...',
    changeRegion: 'অঞ্চল পরিবর্তন',
    changeLang: 'ভাষা',
    readMore: 'আরও পড়ুন',
    minRead: 'মিনিট পড়া',
    bookmarks: 'বুকমার্ক',
    noResults: 'কোনো ফলাফল পাওয়া যায়নি',
    tryDifferent: 'অন্য শব্দ দিয়ে খুঁজুন',
    backHome: 'হোমে ফিরে যান',
    searchResults: 'অনুসন্ধান ফলাফল',
    articlesFound: 'নিবন্ধ পাওয়া গেছে',
    feeds: 'কাস্টম ফিড',
    about: 'আমাদের সম্পর্কে',
    subscribe: 'সাবস্ক্রাইব',
    newsletter: 'নিউজলেটার',
    daily: 'দৈনিক',
    weekly: 'সাপ্তাহিক',
  },
  mr: {
    headlines: 'आजच्या मथळे',
    latest: 'ताज्या बातम्या',
    more: 'अधिक बातम्या',
    localNews: 'स्थानिक बातम्या',
    viewAll: 'सर्व पहा',
    search: 'बातम्या शोधा...',
    changeRegion: 'प्रदेश बदला',
    changeLang: 'भाषा',
    readMore: 'पुढे वाचा',
    minRead: 'मिनिटे वाचन',
    bookmarks: 'बुकमार्क',
    noResults: 'कोणतेही परिणाम सापडले नाहीत',
    tryDifferent: 'वेगळा शब्द शोधा',
    backHome: 'मुख्यपृष्ठावर परत',
    searchResults: 'शोध परिणाम',
    articlesFound: 'लेख सापडले',
    feeds: 'कस्टम फीड',
    about: 'आमच्याबद्दल',
    subscribe: 'सदस्यता घ्या',
    newsletter: 'वृत्तपत्र',
    daily: 'दैनिक',
    weekly: 'साप्ताहिक',
  },
  ur: {
    headlines: 'آج کی سرخیاں',
    latest: 'تازہ خبریں',
    more: 'مزید خبریں',
    localNews: 'مقامی خبریں',
    viewAll: 'سب دیکھیں',
    search: 'خبریں تلاش کریں...',
    changeRegion: 'علاقہ تبدیل کریں',
    changeLang: 'زبان',
    readMore: 'مزید پڑھیں',
    minRead: 'منٹ پڑھنے کا وقت',
    bookmarks: 'بک مارکس',
    noResults: 'کوئی نتیجہ نہیں ملا',
    tryDifferent: 'کوئی اور لفظ تلاش کریں',
    backHome: 'ہوم پر واپس جائیں',
    searchResults: 'تلاش کے نتائج',
    articlesFound: 'مضامین ملے',
    feeds: 'کسٹم فیڈز',
    about: 'ہمارے بارے میں',
    subscribe: 'رکنیت',
    newsletter: 'نیوز لیٹر',
    daily: 'روزانہ',
    weekly: 'ہفتہ وار',
  },
  ar: {
    headlines: 'عناوين اليوم',
    latest: 'آخر الأخبار',
    more: 'المزيد من الأخبار',
    localNews: 'الأخبار المحلية',
    viewAll: 'عرض الكل',
    search: 'البحث في الأخبار...',
    changeRegion: 'تغيير المنطقة',
    changeLang: 'اللغة',
    readMore: 'اقرأ المزيد',
    minRead: 'دقائق للقراءة',
    bookmarks: 'المفضلة',
    noResults: 'لم يتم العثور على نتائج',
    tryDifferent: 'جرب كلمة بحث مختلفة',
    backHome: 'العودة إلى الرئيسية',
    searchResults: 'نتائج البحث',
    articlesFound: 'مقالات',
    feeds: 'خلاصات مخصصة',
    about: 'حول',
    subscribe: 'اشتراك',
    newsletter: 'النشرة الإخبارية',
    daily: 'يومي',
    weekly: 'أسبوعي',
  },
  fr: {
    headlines: 'Titres du jour',
    latest: 'Dernières nouvelles',
    more: "Plus d'articles",
    localNews: 'Nouvelles locales',
    viewAll: 'Voir tout',
    search: 'Rechercher...',
    changeRegion: 'Changer de région',
    changeLang: 'Langue',
    readMore: 'Lire la suite',
    minRead: 'min de lecture',
    bookmarks: 'Favoris',
    noResults: 'Aucun résultat',
    tryDifferent: 'Essayez un autre terme',
    backHome: "Retour à l'accueil",
    searchResults: 'Résultats pour',
    articlesFound: 'articles trouvés',
    feeds: 'Flux personnalisés',
    about: 'À propos',
    subscribe: "S'abonner",
    newsletter: 'Newsletter',
    daily: 'Quotidien',
    weekly: 'Hebdomadaire',
  },
  de: {
    headlines: 'Schlagzeilen',
    latest: 'Neueste Nachrichten',
    more: 'Weitere Nachrichten',
    localNews: 'Lokale Nachrichten',
    viewAll: 'Alle anzeigen',
    search: 'Nachrichten suchen...',
    changeRegion: 'Region ändern',
    changeLang: 'Sprache',
    readMore: 'Weiterlesen',
    minRead: 'Min. Lesezeit',
    bookmarks: 'Lesezeichen',
    noResults: 'Keine Ergebnisse',
    tryDifferent: 'Versuchen Sie einen anderen Begriff',
    backHome: 'Zurück zur Startseite',
    searchResults: 'Suchergebnisse für',
    articlesFound: 'Artikel gefunden',
    feeds: 'Benutzerdefinierte Feeds',
    about: 'Über uns',
    subscribe: 'Abonnieren',
    newsletter: 'Newsletter',
    daily: 'Täglich',
    weekly: 'Wöchentlich',
  },
  es: {
    headlines: 'Titulares de hoy',
    latest: 'Últimas noticias',
    more: 'Más noticias',
    localNews: 'Noticias locales',
    viewAll: 'Ver todo',
    search: 'Buscar noticias...',
    changeRegion: 'Cambiar región',
    changeLang: 'Idioma',
    readMore: 'Leer más',
    minRead: 'min de lectura',
    bookmarks: 'Marcadores',
    noResults: 'Sin resultados',
    tryDifferent: 'Intenta otro término',
    backHome: 'Volver al inicio',
    searchResults: 'Resultados para',
    articlesFound: 'artículos encontrados',
    feeds: 'Feeds personalizados',
    about: 'Acerca de',
    subscribe: 'Suscribirse',
    newsletter: 'Boletín',
    daily: 'Diario',
    weekly: 'Semanal',
  },
  pt: {
    headlines: 'Manchetes de hoje',
    latest: 'Últimas notícias',
    more: 'Mais notícias',
    localNews: 'Notícias locais',
    viewAll: 'Ver tudo',
    search: 'Buscar notícias...',
    changeRegion: 'Mudar região',
    changeLang: 'Idioma',
    readMore: 'Leia mais',
    minRead: 'min de leitura',
    bookmarks: 'Favoritos',
    noResults: 'Nenhum resultado',
    tryDifferent: 'Tente outro termo',
    backHome: 'Voltar ao início',
    searchResults: 'Resultados para',
    articlesFound: 'artigos encontrados',
    feeds: 'Feeds personalizados',
    about: 'Sobre',
    subscribe: 'Inscrever-se',
    newsletter: 'Newsletter',
    daily: 'Diário',
    weekly: 'Semanal',
  },
  zh: {
    headlines: '今日头条',
    latest: '最新新闻',
    more: '更多新闻',
    localNews: '本地新闻',
    viewAll: '查看全部',
    search: '搜索新闻...',
    changeRegion: '更改地区',
    changeLang: '语言',
    readMore: '阅读更多',
    minRead: '分钟阅读',
    bookmarks: '收藏',
    noResults: '没有找到结果',
    tryDifferent: '尝试其他搜索词',
    backHome: '返回首页',
    searchResults: '搜索结果',
    articlesFound: '篇文章',
    feeds: '自定义源',
    about: '关于',
    subscribe: '订阅',
    newsletter: '新闻简报',
    daily: '每日',
    weekly: '每周',
  },
  ja: {
    headlines: '今日のヘッドライン',
    latest: '最新ニュース',
    more: 'もっと見る',
    localNews: 'ローカルニュース',
    viewAll: 'すべて見る',
    search: 'ニュースを検索...',
    changeRegion: '地域を変更',
    changeLang: '言語',
    readMore: '続きを読む',
    minRead: '分で読める',
    bookmarks: 'ブックマーク',
    noResults: '結果が見つかりません',
    tryDifferent: '別のキーワードで検索',
    backHome: 'ホームに戻る',
    searchResults: '検索結果',
    articlesFound: '件の記事',
    feeds: 'カスタムフィード',
    about: '概要',
    subscribe: '購読',
    newsletter: 'ニュースレター',
    daily: '日刊',
    weekly: '週刊',
  },
  ko: {
    headlines: '오늘의 헤드라인',
    latest: '최신 뉴스',
    more: '더 보기',
    localNews: '지역 뉴스',
    viewAll: '모두 보기',
    search: '뉴스 검색...',
    changeRegion: '지역 변경',
    changeLang: '언어',
    readMore: '더 읽기',
    minRead: '분 읽기',
    bookmarks: '북마크',
    noResults: '결과 없음',
    tryDifferent: '다른 검색어를 시도하세요',
    backHome: '홈으로 돌아가기',
    searchResults: '검색 결과',
    articlesFound: '개의 기사',
    feeds: '맞춤 피드',
    about: '소개',
    subscribe: '구독',
    newsletter: '뉴스레터',
    daily: '일간',
    weekly: '주간',
  },
  sw: {
    headlines: 'Vichwa vya Habari',
    latest: 'Habari za Hivi Karibuni',
    more: 'Habari Zaidi',
    localNews: 'Habari za Mtaa',
    viewAll: 'Tazama Zote',
    search: 'Tafuta habari...',
    changeRegion: 'Badilisha eneo',
    changeLang: 'Lugha',
    readMore: 'Soma zaidi',
    minRead: 'dakika za kusoma',
    bookmarks: 'Alamisho',
    noResults: 'Hakuna matokeo',
    tryDifferent: 'Jaribu neno lingine',
    backHome: 'Rudi nyumbani',
    searchResults: 'Matokeo ya utafutaji',
    articlesFound: 'makala zimepatikana',
    feeds: 'Vipasho Maalum',
    about: 'Kuhusu',
    subscribe: 'Jiandikishe',
    newsletter: 'Jarida',
    daily: 'Kila siku',
    weekly: 'Kila wiki',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useLocalStorage('pulsenews-lang', 'en');

  const t = (key) => UI_STRINGS[lang]?.[key] || UI_STRINGS.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, langInfo: LANGUAGES[lang] || LANGUAGES.en }}>
      {children}
    </LanguageContext.Provider>
  );
}

export default function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
